### ISSUE TITLE
No output files 

### ISSUE THREAD

**Issue by slavking** [emma-k-alexandra/Laundry-IDs#1]
Hi, first of all thanks for this wonderfully useful software!

These are the contents of my log file:
```
21:38 $ cat csc_service_works_1_to_1001.log 

================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        9.5.4                                                                          │
  │ Browser:        Electron 94 (headless)                                                         │
  │ Node Version:   v12.22.9 (/usr/bin/node)                                                       │
  │ Specs:          1 found (csc.service.works.spec.js)                                            │
  │ Searched:       cypress/integration/csc.service.works.spec.js                                  │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  csc.service.works.spec.js                                                       (1 of 1)


  CSC Service Works

We stopped running your tests because a plugin crashed.

Your pluginsFile threw an error from: /home/home/Documents/github/Laundry-IDs/cypress/plugins/index.js

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at new NodeError (node:internal/errors:370:5)
    at ChildProcess.target.send (node:internal/child_process:724:16)
    at Object.send (/home/home/.cache/Cypress/9.5.4/Cypress/resources/app/packages/server/lib/plugins/util.js:32:25)
    at EventEmitter.<anonymous> (/home/home/.cache/Cypress/9.5.4/Cypress/resources/app/packages/server/lib/plugins/preprocessor.js:45:16)
    at EventEmitter.emit (node:events:406:35)
    at Object.removeFile (/home/home/.cache/Cypress/9.5.4/Cypress/resources/app/packages/server/lib/plugins/preprocessor.js:119:17)
    at Object.options.onBrowserClose (/home/home/.cache/Cypress/9.5.4/Cypress/resources/app/packages/server/lib/open_project.js:135:40)
    at EventEmitter.<anonymous> (/home/home/.cache/Cypress/9.5.4/Cypress/resources/app/packages/server/lib/browsers/index.js:212:19)
    at Object.onceWrapper (node:events:513:28)
    at EventEmitter.emit (node:events:394:28)
    at BrowserWindow.<anonymous> (/home/home/.cache/Cypress/9.5.4/Cypress/resources/app/packages/server/lib/browsers/electron.js:431:25)
    at Object.onceWrapper (node:events:514:26)
    at BrowserWindow.emit (node:events:406:35)
```

Unfortunately it never seems to scrape anything even after 30 minutes.

**Comment by emma-k-alexandra** [comment]
Hi there, thanks for letting me know about this issue. Just pushed an upgrade to the latest versions of Cypress and Node. Seems to be working again. Let me know if there's any other issues.
